package socketed.common.config;

import net.minecraftforge.common.config.Config;
import net.minecraftforge.common.config.ConfigManager;
import net.minecraftforge.fml.client.event.ConfigChangedEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@Config(modid = socketed.Socketed.MODID, name = socketed.Socketed.MODNAME, category = "")
public class ForgeConfig {

    @Config.Name("Common")
    public static Common COMMON = new Common();

    @Config.Name("Client")
    public static Client CLIENT = new Client();

    @Config.Name("Socketable Items")
    public static IsSocketableConfig SOCKETABLES = new IsSocketableConfig();

    @Config.Name("Socket Rolls")
    public static AddSocketsConfig ADD_SOCKETS = new AddSocketsConfig();

    public static class Common {
        
        @Config.Comment("Maximum amount of sockets any item can have")
        @Config.Name("Max Sockets")
        @Config.RangeInt(min = 1, max = 8)
        public int maxSockets = 8;

        @Config.Comment("Set to false to disable removing gems from sockets")
        @Config.Name("Gems are removable")
        public boolean gemsAreRemovable = true;

        @Config.Comment("Set to true to destroy gems when removing them from sockets")
        @Config.Name("Destroy gems on removal")
        public boolean destroyGemsOnRemoval = false;

        @Config.Comment("How often an item sold by villagers will roll with sockets")
        @Config.Name("Chance for sockets on merchants")
        public float chanceOnMerchant = 0.1F;

        @Config.Comment("How often an item generated by loot pools (excluding socket loot function) will roll with sockets")
        @Config.Name("Chance for sockets on loot")
        public float chanceOnLootGen = 0.1F;

        @Config.Comment("How often an item dropped by mobs will roll with sockets")
        @Config.Name("Chance for sockets on mob drops")
        public float chanceOnMobDrop = 0.1F;

        @Config.Comment("How many sockets an item sold by villagers can roll at maximum")
        @Config.Name("Max amount of sockets on merchants")
        public int maxSocketsOnMerchant = 1;

        @Config.Comment("How many sockets an item generated by loot pools (excluding socket loot function) can roll at maximum")
        @Config.Name("Max amount of sockets on loot")
        public int maxSocketsOnLootGen = 1;

        @Config.Comment("How many sockets an item dropped by mobs can roll at maximum")
        @Config.Name("Max amount of sockets on mob drops")
        public int maxSocketsOnMobDrop = 1;

        @Config.Comment("Add weights for tiers 0,1,2,3 of sockets to roll on items that can have sockets")
        @Config.Name("Socket Tier Weights")
        public int[] socketTierWeights = {1, 5, 2, 1};
    }

    public static class Client {

    }

    @Mod.EventBusSubscriber(modid = socketed.Socketed.MODID)
    private static class EventHandler {
        
        @SubscribeEvent
        public static void onConfigChanged(ConfigChangedEvent.OnConfigChangedEvent event) {
            if(event.getModID().equals(socketed.Socketed.MODID)) {
                ConfigManager.sync(socketed.Socketed.MODID, Config.Type.INSTANCE);
            }
        }
    }
}